[package]
name = "practice_Check-Sentence"
version = "0.1.0"
authors = ["fen-harel"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
